CREATE TABLE PROPERTIES
 (	APPLICATION VARCHAR2(255 BYTE) NOT NULL ENABLE,
PROFILE VARCHAR2(255 BYTE) NOT NULL ENABLE,
LABEL VARCHAR2(255 BYTE) NOT NULL ENABLE,
'KEY' VARCHAR2(255 BYTE) NOT NULL ENABLE,
'VALUE' VARCHAR2(255 BYTE),
 CONSTRAINT PROPERTIES_PK PRIMARY KEY (APPLICATION, PROFILE, LABEL, KEY)
 ) ;